# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

notify:
  - name: MIESZKANIE
    platform: group
    services:
      - service: mobile_app_sm_g970f

alarm_control_panel:
  - platform: manual
    name: Alarm
    code_arm_required: false
    arming_time: 30
    delay_time: 30
    trigger_time: 120
    disarm_after_trigger: false
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
